redis:
  protocol: tcp
  address: 127.0.0.1:6379
  expire: 3600
splash:
  base-url: "http://127.0.0.1:8050/"
  ping-url: "_ping" #this endpoint is used for checking if splash service is alive 
  render-html: "render.html"
  render-json: "render.json"
  username: "user"
  userpass: "userpass"
  timeout: 20
  resource-timeout: 30
  wait: 1 #wait parameter should be something more than default 0,5 value as it is not enough to load js scripts
parser:
  CSV:
    comma: ","