sudo: required

language: go

services:
  - docker

go:
  - 1.9.x

before_install:
  - go get -v github.com/golang/lint/golint
  - go get -t -v ./...
  - docker-compose -f docker-compose-test.yml up -d

script: ./test.sh
 
after_success:
  - bash <(curl -s https://codecov.io/bash)