sudo: required

language: go

services:
  - docker

go:
  - 1.9.x

before_install:
  - docker pull scrapinghub/splash
  - docker run -d -it -p 5023:5023 -p 8050:8050 -p 8051:8051 scrapinghub/splash
  - go get -v github.com/golang/lint/golint
  - go get -t -v ./...

script: ./test.sh
 
after_success:
  - bash <(curl -s https://codecov.io/bash)