version: '3'

services:
  chrome:
    image: justinribeiro/chrome-headless
    cap_add:
      - SYS_ADMIN
    restart: always
    ports:
      - "9222:9222"

    

  fetch:
    image: slotix/dfk-fetch
    environment:
      - CHROME=chrome:9222
      - DFK_FETCH=fetch:8000
      - DISKV_BASE_DIR=./diskv
    volumes:
      - ./diskv:/diskv
    ports:
      - "8000:8000"
    #env_file: 
     # - .env
    depends_on:
      - chrome
    restart: always
  
  parse:
    image: slotix/dfk-parse
    environment:
      - DFK_FETCH=fetch:8000
      - DFK_PARSE=parse:8001
      - DISKV_BASE_DIR=./diskv
      - RESULTS_DIR=./results
    volumes:
      - ./diskv:/diskv
      - ./results:/results
    ports:
      - "8001:8001"
    depends_on:
      - fetch
    restart: always
volumes:
  diskv:
  results: