version: '3'

services:
  chrome:
    image: justinribeiro/chrome-headless
    cap_add:
      - SYS_ADMIN
    restart: always
    ports:
      - "9222:9222"

  cassandra:
    #image: cassandra
    build: ./storage/cassandra
    restart: always
    environment:
      # define cluster topology
      - CASSANDRA_CLUSTER_NAME=dfk-db
      - CASSANDRA_DC=dfk-east
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch

      # define gossip entrypoints
      #- CASSANDRA_SEEDS=cassandra,cassandra2,cassandra3
      - CASSANDRA_SEEDS=cassandra 

      # define heap size for local development
      - MAX_HEAP_SIZE=500M
      - HEAP_NEWSIZE=100M

      # open JMX port for access by Reaper
      # WARNING: this is unsafe in production without proper firewall settings
      - LOCAL_JMX=yes    

    ports:
      - "7199:7199" # JMX
      - "7000:7000" # cluster communication
      - "7001:7001" # cluster communication (SSL)
      - "9042:9042" # native protocol clients
      - "9160:9160" # thrift clients
    volumes:
      - ./storage/cassandra/db:/var/lib/cassandra
      - ./storage/cassandra/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  fetch:
    image: slotix/dfk-fetch
    environment:
      - CHROME=chrome:9222
      - DFK_FETCH=fetch:8000
      - DISKV_BASE_DIR=./diskv
    volumes:
      - ./diskv:/diskv
    ports:
      - "8000:8000"
    #env_file: 
     # - .env
    depends_on:
      - chrome
    restart: always
  
  parse:
    image: slotix/dfk-parse
    environment:
      - DFK_FETCH=fetch:8000
      - DFK_PARSE=parse:8001
      - DISKV_BASE_DIR=./diskv
      - RESULTS_DIR=./results
    volumes:
      - ./diskv:/diskv
      - ./results:/results
    ports:
      - "8001:8001"
    depends_on:
      - fetch
    restart: always
volumes:
  diskv:
  results: