service: dfk
package:
  artifact: package.zip
provider:
  name: aws
  runtime: python2.7
  stage: ${env:ENV}
  region: ${env:AWS_REGION}
functions:
  fetch:
    handler: handler.Handler
    environment:
      SPLASH: ${env:SPLASH}
      SPLASH_TIMEOUT: ${env:SPLASH_TIMEOUT}
      SPLASH_RESOURCE_TIMEOUT: ${env:SPLASH_RESOURCE_TIMEOUT}
      SPLASH_WAIT: ${env:SPLASH_WAIT}
    events:
      - http:
          path: fetch
          method: post
          cors: true
      - http:
          path: parse
          method: post
          cors: true